from . import test_backend
from . import test_cart
from . import test_cart_copy
from . import test_cart_item
from . import test_address
from . import test_partner_access_info
from . import test_product
from . import test_product_filter
from . import test_sale
from . import test_sale_cancel
from . import test_shopinvader_category
from . import test_shopinvader_variant_binding_wizard
from . import test_shopinvader_category_binding_wizard
from . import test_customer
from . import test_shopinvader_partner
from . import test_shopinvader_variant_seo_title
from . import test_res_partner
from . import test_invoice
from . import test_shopinvader_partner_binding
from . import test_notification
from . import test_salesman_notification
from . import test_search
from . import test_utils
from . import test_settings
