# Copyright 2023 Akretion (https://www.akretion.com).
# @author Matthieu SAISON <matthieu.saison@akretion.com>
# License AGPL-3.0 or later (https: //www.gnu.org/licenses/agpl).

import logging

from odoo import api, models

_logger = logging.getLogger(__name__)

SHOPINVADER_V1_BASE_XMLID = [
    "account_analytic_0",
    "fiscal_position_0",
    "fiscal_position_1",
    "fiscal_position_2",
    "position_tax_1",
    "position_tax_2",
    "tax_1",
    "tax_2",
    "tax_3",
    "action_cart",
    "action_sale",
    "act_open_shopinvader_cart_step_view",
    "act_open_shopinvader_partner_view",
    "shopinvader_config_settings_act_window",
    "shopinvader_partner_binding_act_window",
    "act_open_shopinvader_cart_step_view_tree",
    "act_open_shopinvader_partner_view_form",
    "act_open_shopinvader_partner_view_tree",
    "module_category_shopinvader",
    "shopinvader_backend_comp_rule",
    "shopinvader_partner_comp_rule",
    "menu_cart",
    "menu_sale",
    "menu_shopinvader_cart_step",
    "menu_shopinvader_config",
    "menu_shopinvader_config_cart",
    "menu_shopinvader_config_partners",
    "menu_shopinvader_config_technical",
    "menu_shopinvader_orders",
    "menu_shopinvader_partner",
    "menu_shopinvader_root",
    "shopinvader_config_settings_menu",
    "res_config_settings_view_form",
    "res_partner_view_form",
    "sale_order_view_form",
    "shopinvader_cart_step_view_search",
    "shopinvader_cart_step_view_tree",
    "shopinvader_partner_binding_form_view",
    "shopinvader_partner_view_form",
    "shopinvader_partner_view_search",
    "shopinvader_partner_view_tree",
    "view_order_tree",
    "view_quotation_tree",
    "view_res_partner_filter",
    "view_sales_order_filter",
    "view_shop_order_tree",
    "view_shop_quotation_tree",
    "mail_activity_review_customer",
    "email_address_created_notification",
    "email_address_updated_notification",
    "email_cart_notification",
    "email_customer_updated_notification",
    "email_invoice_notification",
    "email_new_customer_welcome_notification",
    "email_sale_notification",
    "pricelist_1",
    "item_1",
    "channel_shopinvader",
    "channel_shopinvader_bind_products",
    "channel_shopinvader_notification",
    "job_function_shopinvader_bind_selected_products",
    "job_function_shopinvader_bind_single_product",
    "job_function_shopinvader_notification_send",
    "country_group_1",
    "group_shopinvader_manager",
    "group_shopinvader_partner_binding",
    "anonymous",
    "partner_1",
    "partner_1_address_1",
    "partner_1_address_2",
    "partner_2",
    "partner_2_address_1",
    "sale_order_1",
    "sale_order_2",
    "sale_order_3",
    "sale_order_line_1",
    "sale_order_line_2",
    "sale_order_line_3",
    "sale_order_line_4",
    "sale_order_line_5",
    "sale_order_line_6",
    "sale_order_line_7",
    "backend_1",
    "backend_2",
    "cart_address",
    "cart_checkout",
    "cart_end",
    "cart_index",
    "cart_login",
    "shopinvader_notification_address_created",
    "shopinvader_notification_address_updated",
    "shopinvader_notification_cart",
    "shopinvader_notification_customer_updated",
    "shopinvader_notification_invoice",
    "shopinvader_notification_new_customer_welcome",
    "shopinvader_notification_sale",
    "shopinvader_partner_1",
    "shopinvader_partner_2",
    "model_shopinvader_backend",
    "model_sale_order",
    "model_shopinvader_partner_binding",
    "model_shopinvader_partner_binding_line",
    "model_res_partner",
    "model_res_config_settings",
    "model_sale_order_line",
    "model_account_move",
    "model_track_external_mixin",
    "model_shopinvader_notification",
    "model_shopinvader_cart_step",
    "model_shopinvader_partner",
]

SHOPINVADER_V1_PRODUCT_XMLID = [
    "action_shopinvader_backend",
    "act_open_shopinvader_category_view",
    "product_filter_action",
    "shopinvader_category_binding_wizard_act_window",
    "shopinvader_category_unbinding_wizard_act_window",
    "shopinvader_product_act_window",
    "shopinvader_variant_act_window",
    "shopinvader_variant_binding_wizard_act_window",
    "shopinvader_variant_unbinding_wizard_act_window",
    "ir_exp_shopinvader_category",
    "ir_exp_shopinvader_variant",
    "ir_exp_shopinvader_category_childs_childs_childs_id",
    "ir_exp_shopinvader_category_childs_childs_childs_name",
    "ir_exp_shopinvader_category_childs_childs_childs_url_key",
    "ir_exp_shopinvader_category_childs_childs_id",
    "ir_exp_shopinvader_category_childs_childs_name",
    "ir_exp_shopinvader_category_childs_childs_url_key",
    "ir_exp_shopinvader_category_childs_id",
    "ir_exp_shopinvader_category_childs_name",
    "ir_exp_shopinvader_category_childs_url_key",
    "ir_exp_shopinvader_category_description",
    "ir_exp_shopinvader_category_filter_ids_display_name",
    "ir_exp_shopinvader_category_filter_ids_help",
    "ir_exp_shopinvader_category_filter_ids_name",
    "ir_exp_shopinvader_category_level",
    "ir_exp_shopinvader_category_meta_description",
    "ir_exp_shopinvader_category_meta_keywords",
    "ir_exp_shopinvader_category_name",
    "ir_exp_shopinvader_category_parent_name",
    "ir_exp_shopinvader_category_parent_parent_name",
    "ir_exp_shopinvader_category_parent_parent_parent_name",
    "ir_exp_shopinvader_category_parent_parent_parent_url_key",
    "ir_exp_shopinvader_category_parent_parent_shopinvader_parent_id",
    "ir_exp_shopinvader_category_parent_parent_url_key",
    "ir_exp_shopinvader_category_parent_shopinvader_parent_id",
    "ir_exp_shopinvader_category_parent_url_key",
    "ir_exp_shopinvader_category_record_id",
    "ir_exp_shopinvader_category_redirect_url_key",
    "ir_exp_shopinvader_category_seo_title",
    "ir_exp_shopinvader_category_sequence",
    "ir_exp_shopinvader_category_shopinvader_parent_id",
    "ir_exp_shopinvader_category_short_description",
    "ir_exp_shopinvader_category_subtitle",
    "ir_exp_shopinvader_category_url_key",
    "ir_exp_shopinvader_description",
    "ir_exp_shopinvader_name",
    "ir_exp_shopinvader_short_description",
    "ir_exp_shopinvader_short_name",
    "ir_exp_shopinvader_variant_attributes",
    "ir_exp_shopinvader_variant_categs_id",
    "ir_exp_shopinvader_variant_categs_name",
    "ir_exp_shopinvader_variant_categs_parent_id",
    "ir_exp_shopinvader_variant_categs_url_key",
    "ir_exp_shopinvader_variant_default_code",
    "ir_exp_shopinvader_variant_main",
    "ir_exp_shopinvader_variant_meta_description",
    "ir_exp_shopinvader_variant_meta_description",
    "ir_exp_shopinvader_variant_meta_keywords",
    "ir_exp_shopinvader_variant_model_name",
    "ir_exp_shopinvader_variant_price",
    "ir_exp_shopinvader_variant_record_id",
    "ir_exp_shopinvader_variant_redirect_url_key",
    "ir_exp_shopinvader_variant_seo_title",
    "ir_exp_shopinvader_variant_url_key",
    "ir_exp_shopinvader_variant_variant_count",
    "model_product_category",
    "model_product_filter",
    "model_product_product",
    "model_product_template",
    "model_seo_title_mixin",
    "model_shopinvader_backend",
    "model_shopinvader_binding",
    "model_shopinvader_category",
    "model_shopinvader_category_binding_wizard",
    "model_shopinvader_category_unbinding_wizard",
    "model_shopinvader_product",
    "model_shopinvader_variant",
    "model_shopinvader_variant_binding_wizard",
    "model_shopinvader_variant_unbinding_wizard",
    "shopinvader_category_comp_rule",
    "shopinvader_product_comp_rule",
    "shopinvader_variant_comp_rule",
    "menu_product_filter_action",
    "menu_shopinvader_backend",
    "menu_shopinvader_category",
    "menu_shopinvader_config_products",
    "menu_shopinvader_products",
    "shopinvader_product_menu",
    "shopinvader_variant_menu",
    "product_category_view_form",
    "product_filter_view_form",
    "product_filter_view_tree",
    "product_product_form_view",
    "shopinvader_backend_view_form",
    "shopinvader_category_binding_wizard_form_view",
    "shopinvader_category_unbinding_wizard_form_view",
    "shopinvader_product_form_view",
    "shopinvader_product_kanban_view",
    "shopinvader_product_search_view",
    "shopinvader_product_tree_view",
    "shopinvader_variant_binding_wizard_form_view",
    "shopinvader_variant_form_view",
    "shopinvader_variant_kanban_view",
    "shopinvader_variant_search_view",
    "shopinvader_variant_tree_view",
    "shopinvader_variant_unbinding_wizard_form_view",
    "view_product_template_form",
    "view_shopinvader_backend_tree",
    "view_shopinvader_category_form",
    "view_shopinvader_category_search",
    "view_shopinvader_category_tree",
    "product_attribute_value_color_blue",
    "product_attribute_value_color_brown",
    "product_attribute_value_color_grey",
    "product_attribute_value_color_red",
    "product_attribute_value_color_white",
    "product_attribute_value_color_yellow",
    "product_category_21",
    "product_category_22",
    "product_category_226",
    "product_category_227",
    "product_category_228",
    "product_category_23",
    "product_category_24",
    "product_category_25",
    "product_category_26",
    "product_category_27",
    "product_category_28",
    "product_category_29",
    "product_category_30",
    "product_category_31",
    "product_filter_1",
    "product_filter_2",
    "product_product_armchair_mid_century_blue",
    "product_product_armchair_mid_century_grey",
    "product_product_armchair_mid_century_red",
    "product_product_armchair_mid_century_yellow",
    "product_product_chair_mid_century_black",
    "product_product_chair_mid_century_blue",
    "product_product_chair_mid_century_red",
    "product_product_chair_mid_century_white",
    "product_product_chair_vortex_blue",
    "product_product_chair_vortex_white",
    "product_product_coffee_table_caftman_brown",
    "product_product_park_entertainment",
    "product_product_round_table_mid_century_white",
    "product_product_table_walmut",
    "product_product_thelma_black",
    "product_product_thelma_grey",
    "product_product_thelma_red",
    "product_product_tv_cabinet_cmcharper_brown",
    "product_product_tv_cabinet_concept_design_white",
    "product_product_tv_cabinet_mid_century_brown",
    "product_product_tv_cabinet_shaker_wood_brown",
    "product_product_tv_cabinet_shaker_wood_grey",
    "product_product_tv_cbinet_ameriwood",
    "product_product_tv_stand_wood_and_glass_white",
    "product_product_park_entertainment_product_template",
    "product_product_tv_cbinet_ameriwood_product_template",
    "product_template_armchair_mid_century",
    "product_template_chair_mid_century",
    "product_template_chair_vortex",
    "product_template_coffee_table_caftman",
    "product_template_round_table_mid_century",
    "product_template_thelma",
    "product_template_tv_cabinet_cmcharper",
    "product_template_tv_cabinet_concept_design",
    "product_template_tv_cabinet_mid_century",
    "product_template_tv_cabinet_shaker_wood",
    "product_template_tv_stand_wood_and_glass",
    "product_template_armchair_mid_century_product_template_attribute_line_color",
    "product_template_chair_mid_century_product_template_attribute_line_color",
    "product_template_chair_vortex_product_template_attribute_line_color",
    "product_template_coffee_table_caftman_product_template_attribute_line_color",
    "product_template_round_table_mid_century_product_template_attribute_line_color",
    "product_template_thelma_product_template_attribute_line_color",
    "product_template_tv_cabinet_cmcharper_product_template_attribute_line_color",
    "product_template_tv_cabinet_concept_design_product_template_attribute_line_color",
    "product_template_tv_cabinet_mid_century_product_template_attribute_line_color",
    "product_template_tv_cabinet_shaker_wood_product_template_attribute_line_color",
    "product_template_tv_stand_wood_and_glass_product_template_attribute_line_color",
    "product_template_armchair_mid_century_attribute_color_blue",
    "product_template_armchair_mid_century_attribute_color_grey",
    "product_template_armchair_mid_century_attribute_color_red",
    "product_template_armchair_mid_century_attribute_color_yellow",
    "product_template_chair_mid_century_attribute_color_black",
    "product_template_chair_mid_century_attribute_color_blue",
    "product_template_chair_mid_century_attribute_color_red",
    "product_template_chair_mid_century_attribute_color_white",
    "product_template_chair_vortex_attribute_color_blue",
    "product_template_chair_vortex_attribute_color_white",
    "product_template_coffee_table_caftman_attribute_color_brown",
    "product_template_round_table_mid_century_attribute_color_blue",
    "product_template_thelma_attribute_color_black",
    "product_template_thelma_attribute_color_grey",
    "product_template_thelma_attribute_color_red",
    "product_template_tv_cabinet_cmcharper_attribute_color_brown",
    "product_template_tv_cabinet_concept_design_attribute_color_white",
    "product_template_tv_cabinet_mid_century_attribute_color_brown",
    "product_template_tv_cabinet_shaker_wood_attribute_color_brown",
    "product_template_tv_cabinet_shaker_wood_attribute_color_grey",
    "product_template_tv_stand_wood_and_glass_attribute_color_blue",
]


def mapped_xml_id(xmlid):
    # fix the existing ref to shopinvader by new name
    module, name = xmlid.split(".")
    if module == "shopinvader":
        if name in SHOPINVADER_V1_PRODUCT_XMLID:
            _logger.warning(
                f"Old name for shopinvader is used: {xmlid} \n"
                "Please rename module ref to "
                "shopinvader_product_binding"
            )
            xmlid = f"shopinvader_product_binding.{name}"
        elif name in SHOPINVADER_V1_BASE_XMLID:
            xmlid = f"shopinvader_restapi.{name}"
            _logger.warning(
                f"Old name for shopinvader is used: {xmlid} \n"
                "Please rename module ref to shopinvader_restapi"
            )
    return xmlid


class IrModelData(models.Model):
    _inherit = "ir.model.data"

    @api.model
    def xmlid_lookup(self, xmlid):
        xmlid = mapped_xml_id(xmlid)
        return super().xmlid_lookup(xmlid)


class IrFieldsConverter(models.AbstractModel):
    _inherit = "ir.fields.converter"

    def _xmlid_to_record_id(self, xmlid, model):
        xmlid = mapped_xml_id(xmlid)
        return super()._xmlid_to_record_id(xmlid, model)
