#!/usr/bin/env python

import os

from algoliasearch import algoliasearch

client = algoliasearch.Client(
    os.environ["ALGOLIA_APP"], os.environ["ALGOLIA_API_KEY"]
)
job = os.environ["TRAVIS_JOB_NUMBER"].replace(".", "_")
client.delete_index("%s-algolia-product" % job)
client.delete_index("%s-algolia-category" % job)
